language: node_js
node_js: 10
dist: trusty
sudo: required
addons:
  chrome: stable
branches:
  only:
  - master
  - /^v.*$/
script:
- npm run lint
- npm run test-sauce
after_success:
- frauci-update-version && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME: Brightspacehypermediacomponents
  - REPO_NAME: sequences
  - DEFAULT_INCREMENT: patch
  # GITHUB_RELEASE_TOKEN (temp-hypermedia-sequences)
  - secure: i4Xu1NOn8VeasngHVj3WcZJ76ANv8HFckvpSApyr9KIJX2umXNpCKRUKHiHr29HCRetgUI83Xaw2MBueS+1UKcGimgt+Yc5gOJySn73GAzNjaTIhYNQZ54WypLQOg0KAsWXswCGYXCJlicj/IBONt1A1cD80Dde8kPkVA/Iu4UG0utOk90aAl6mDWaAs1fqdCWomXCsnolv0vhfU7bsSZKguah3oVAuxww0I8LxKmdzRzJXKm+MhqoAgRb+1D2FBOrZiMoH6I4KZfHGLwU3XLB2MLE7UlvCxh9EIuSB3DuDmsT/x9R+Sp+uLpbz+lqKlJw5coU+c3I+vtWXE5h3AJy5SGdqvR+JgdV40ahG+3rsqSq7wACauj2l72rCpkGn8sfZYkNEXg5zuIeWlsZIcW+MRJy9wqLJOyfkGWtEoGEe12yGKvh7U14fER/ivgqj6QclfMwrKKV8FStgYdSicn+ERboOWU/uG2ruQiPzglQqwSY291SR8Pfgr997Iq5pzMnN9jbk9bG9DwroOm9iXL3G30yLVPoCI1HMHatGtkNXn2x2NH2hNxWl/OKYNBBSsoXVlu6NV+41QcIH3m2fhjkAJs4+YcaZeHq38Oes+qPrkptC8tXmrJHc5pkCE8GP3rqiakJvTUtK4/CzWmRoIjxNGhGBPJWOsPh0v0M2ZDRo=
  # SAUCE_USERNAME = team_mango
  - secure: Ss6mkOcUrZ5HeCAyRTB5g4JO0dpyyvJGZ/Bdyvu9yj3k9qpy0sJS6jw1BSChA09vwHTsowbLKqSvcAaW6DMA3rezL/z+Kq4PNw97Hxbz157fPwWWGhPNjtdjl1mMwnTMW1I4iqGNfYm/vRAv6I+QcFvW8e/UvBnrNqO6zS09W4yvn/UItgoddXWhHx3VlYTO0qQHzon3QMO1NdHeUX9T36lc5YiENiRoJ+SjNqWsZzqvI/Ui8kM5pRMD3zvWrJ8fWabrb5J6B/QxAmTmW4ytZISFNwmqm9poWJIM20GJKNbQR/KzjwigPKLSuhK8PeFJYHqys/5QennAxwntKScT8YXozvaTpAfb/J2og0MOn7IbGHv/9AnkhJXMjanPUJmjpydsYu6tXCnL/xLz4M1gOrItYi0uEHKC8OJcyMJAYMRePj7t0fjOJw6ImPD3VFUfdBYecyBeP+hVRJ+pz0XMBTVVX94+nafrh//Ai6UzmYJZXqe8TorMnNxo+87YD+mM1IYRcZf4hMQ6gwxeIxQEffhxthip3PoJRedzxE1hAlezgTxN6epmx5uUMouhZh1f50QysMyUvsewcGUSbo2I2RdfJrBjyyKDPOfC4K3aWgYZrLDcY+UhNei+99TLVSaSGeniBlTXHza67h4+Wojm0mJuEgAK7k8Wp62r0X4sXec=
  # SAUCE_ACCESS_KEY
  - secure: byubfacEHMkQ5XyCwl2mWUQykA6+VpsWcWPn1BVkfF+ZEUWXsvgM4SOdXgq5wsS/+kFZWXcpSYc32HxUUQKoLc9oAGLLydJqAC49oWbhQoZbaMPDVMH6RhUjvGH2zmayGZZPqAzXTwC9dENjzr/7P/w/axnZG8qaGYmTOs0B0dB3eOhdmMx7drtCudgQs8ntFm2iTE+vnb581w+fCcZxiX9YRTrKnCucsYl96esFIjRCeElXfIPuhglGxPUYqd6afEd5XafwgcCNQQ+SeDBg4o2KSRXEJk8P1DdvUFuky0rCPVUzPT4ItxauLlFXxJ4sdL6XPiBTSA/jpRw9jXcxdkql3jvveIrlCtzQy+yEBgGcKN9uXGlcEgCfDIAdJkSFGdZncWSqzaencWSRd1aUDImBfxJym7Kld6nWevTO23NFxhCIl6jxGaESV4sGT2itd84UmHx2X+CHEFkuiprl5vZ++vXAAcdpML7U9/ZhtmU81sEp2zZyg0C6kXvyOrLDJBZuMjyFo504MS3q7+55pI4xSfa5THjAz9mkgdqEoO072eSKIPRDv4EBaUcGskTD7P2snum5FgduP0U0HL0KSBC+AlDgiQyqptjPfx60t2UPGi7hHNWebh64orAgKyCy2am+Q1E//ntWpTDDKpZeDUiyxACB5WVF3BIDzI2FZ9I=
