language: node_js
node_js: 10
dist: trusty
sudo: required
addons:
  chrome: stable
branches:
  only:
  - master
  - /^v.*$/
script:
- npm run lint
- npm run test-sauce
after_success:
- frauci-update-version && export TRAVIS_TAG=$(frauci-get-version)
deploy:
  provider: releases
  api_key: "$GITHUB_RELEASE_TOKEN"
  on:
    tags: true
env:
  global:
  - OWNER_NAME: Brightspacehypermediacomponents
  - REPO_NAME: sequences
  - DEFAULT_INCREMENT: patch
  # GITHUB_RELEASE_TOKEN (9737......e79d)
  - secure: X3aD9X/kD366xLqBhHrO4VVQIWfGg+xJ9XoUt092cS4X14BBkMs1pwb7vd6/5Fq/69OawayqTkUcvuV6KTFfrq+lAY004hCqR2SyspilgyG05p2KO4X0pGMC2lx3bBqIu3AwFf3zWe0/KFQHlH7DT9y4pYvXyDMvC+492+45Sm6zDeEXHzg7d9Hyi0d4O1ypg7rLY5SKoEIgb/8ZRjR8uwUfmW+6qtMsdTyh2xo5zH8thqevcCG5t+DQQv3/y6KR/tCm6xCsEHOFUud0naDH+PAAKLe8q9Abo2pQZA5mp5UbQDVk2N63pJo+HKenOwVX3L91t9dsIZNO/nhsSKFv3k80dKCllpr+J4vtpKjSdh1x+yaS1L7EGRYmGcP8bx4UMJYS6ry1czmP03epFeMH0jBsnbhtB87gULDhe+FVnwWKPZ5dZr23fZP3zqgaWEG3VShywmBH2p7o+FhmQCijBr/qQEsPRfJHMhr5H5KBvDJEBT/gqzx3V4ln/YEpv1Nf1w5FWNbBJmcuxO7SDrDEP4DtF5QwnjwpFiEl+WxQNMTk7sjdl9YD3XEb8//DJyks0riFNoLOX6I/XFrsHXoMJoZXkUPO7P2zL7pDSpi54aOO54cgV6gztbRoHGCW0bZr2VYER98c0eh8d+qA34vzMMHsbMEVfyRxxRQ3UuDUgQY=
  # SAUCE_USERNAME = team_mango
  - secure: Ss6mkOcUrZ5HeCAyRTB5g4JO0dpyyvJGZ/Bdyvu9yj3k9qpy0sJS6jw1BSChA09vwHTsowbLKqSvcAaW6DMA3rezL/z+Kq4PNw97Hxbz157fPwWWGhPNjtdjl1mMwnTMW1I4iqGNfYm/vRAv6I+QcFvW8e/UvBnrNqO6zS09W4yvn/UItgoddXWhHx3VlYTO0qQHzon3QMO1NdHeUX9T36lc5YiENiRoJ+SjNqWsZzqvI/Ui8kM5pRMD3zvWrJ8fWabrb5J6B/QxAmTmW4ytZISFNwmqm9poWJIM20GJKNbQR/KzjwigPKLSuhK8PeFJYHqys/5QennAxwntKScT8YXozvaTpAfb/J2og0MOn7IbGHv/9AnkhJXMjanPUJmjpydsYu6tXCnL/xLz4M1gOrItYi0uEHKC8OJcyMJAYMRePj7t0fjOJw6ImPD3VFUfdBYecyBeP+hVRJ+pz0XMBTVVX94+nafrh//Ai6UzmYJZXqe8TorMnNxo+87YD+mM1IYRcZf4hMQ6gwxeIxQEffhxthip3PoJRedzxE1hAlezgTxN6epmx5uUMouhZh1f50QysMyUvsewcGUSbo2I2RdfJrBjyyKDPOfC4K3aWgYZrLDcY+UhNei+99TLVSaSGeniBlTXHza67h4+Wojm0mJuEgAK7k8Wp62r0X4sXec=
  # SAUCE_ACCESS_KEY
  - secure: byubfacEHMkQ5XyCwl2mWUQykA6+VpsWcWPn1BVkfF+ZEUWXsvgM4SOdXgq5wsS/+kFZWXcpSYc32HxUUQKoLc9oAGLLydJqAC49oWbhQoZbaMPDVMH6RhUjvGH2zmayGZZPqAzXTwC9dENjzr/7P/w/axnZG8qaGYmTOs0B0dB3eOhdmMx7drtCudgQs8ntFm2iTE+vnb581w+fCcZxiX9YRTrKnCucsYl96esFIjRCeElXfIPuhglGxPUYqd6afEd5XafwgcCNQQ+SeDBg4o2KSRXEJk8P1DdvUFuky0rCPVUzPT4ItxauLlFXxJ4sdL6XPiBTSA/jpRw9jXcxdkql3jvveIrlCtzQy+yEBgGcKN9uXGlcEgCfDIAdJkSFGdZncWSqzaencWSRd1aUDImBfxJym7Kld6nWevTO23NFxhCIl6jxGaESV4sGT2itd84UmHx2X+CHEFkuiprl5vZ++vXAAcdpML7U9/ZhtmU81sEp2zZyg0C6kXvyOrLDJBZuMjyFo504MS3q7+55pI4xSfa5THjAz9mkgdqEoO072eSKIPRDv4EBaUcGskTD7P2snum5FgduP0U0HL0KSBC+AlDgiQyqptjPfx60t2UPGi7hHNWebh64orAgKyCy2am+Q1E//ntWpTDDKpZeDUiyxACB5WVF3BIDzI2FZ9I=
